services:

  api-gateway:
    image: matteusmachhado/api-gateway:latest
    container_name: api-gateway
    build:
      context: ../
      dockerfile: ./src/api gateway/Project.WMS.Stock/Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5002;http://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
    volumes:
    - ./certs:/https:ro
    depends_on:
      - authentication-provider-web-api
      - order-web-api
      - product-web-api
    networks:
      - local

  authentication-provider-web-api:
    image: matteusmachhado/authentication-provider-web-api:latest
    container_name: authentication-provider-web-api
    build:
      context: ../
      dockerfile: ./src/services/Project.WMS.AuthenticationProvider.WebAPI/Dockerfile
    ports:
      - "7101:7101"
      - "7102:7102"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7102;http://+:7101
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
    volumes:
      - ./certs:/https:ro
    networks:
      - local

  order-web-api:
    image: matteusmachhado/order-web-api:latest
    container_name: order-web-api
    build:
      context: ../
      dockerfile: ./src/services/Project.WMS.Order.WebAPI/Dockerfile
    ports:
      - "8101:8101"
      - "8102:8102"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:8102;http://+:8101
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
    volumes:
      - ./certs:/https:ro
    networks:
      - local

  product-web-api:
    image: matteusmachhado/product-web-api:latest
    container_name: product-web-api
    build:
      context: ../
      dockerfile: ./src/services/Project.WMS.Product.WebAPI/Dockerfile
    ports:
      - "6101:6101"
      - "6102:6102"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:6102;http://+:6101
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
    volumes:
      - ./certs:/https:ro
    networks:
      - local

networks:
  local: